{{- if and .Values.istio.enabled .Values.upstream.alertmanager.enabled .Values.istio.alertmanager.enabled -}}
{{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "kube-alertmanager" }}
{{- $servicePort := .Values.upstream.alertmanager.service.port -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-alertmanager
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "kube-alertmanager" }}
  {{- include "kube-prometheus-stack.labels" . | indent 4 }}
  {{- if .Values.istio.alertmanager.labels }}
{{ toYaml .Values.istio.alertmanager.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.alertmanager.annotations }}
  annotations:
{{ toYaml .Values.istio.alertmanager.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.alertmanager.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.alertmanager.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
        - destination:
            port:
              number: {{ .Values.istio.alertmanager.port | default .Values.upstream.alertmanager.service.port  }}
            host: {{ .Values.istio.alertmanager.service | default $serviceName }}.{{ .Values.istio.alertmanager.namespace | default  .Release.Namespace }}.svc.cluster.local
{{- end }}
